<?php session_start(); ?>
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>Dashboard - Usuarios</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <link rel='stylesheet' href='//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.1.0/css/font-awesome.min.css'>
  <link rel="stylesheet" href="<?php echo Conexion::ruta(); ?>/css/dashboard.css">
  <link rel="stylesheet" href="<?php echo Conexion::ruta(); ?>/css/table.css">

</head>

<body>
  <!-- partial:index.partial.html -->

  <body>
    <div id="menu-overlay"></div>
    <div id="menu-toggle" class="closed" data-title="Menu">
      <i class="fa fa-bars"></i>
      <i class="fa fa-times"></i>
    </div>

    <!-- MENU LATERAL -->
      <?php
        include "./view/menusidebar.phtml"; 
      ?>
     <!-- MENU LATERAL -->

    <section id="content">
      <div class="table">
        <div class="table-header">
          <div class="left-content">
            <h2>Caracterización</h2>
          </div>
        </div>
        <div class="table-wrapper">
          <table>
            <thead>
              <tr>
                <th>Id caracterización</th>
                <th>altura</th>
                <th>Peso</th>
                <th>Diametro pierna</th>
                <th>Antecedentes</th>
                <th>Puntaje</th>
                <th>Id caracterización tipo amputación</th>
                <th>Opciones</th>
              </tr>
            </thead>
                <?php
                    for($i = 0; $i < sizeof($carac); $i++){
                ?>
                <tbody>
                    <tr>
                        <td><?php echo $carac[$i]['id_caracterizacion']; ?></td>
                        <td><?php echo $carac[$i]['altura']; ?></td>
                        <td><?php echo $carac[$i]['peso'] ?></td>
                        <td><?php echo $carac[$i]['diametro_pierna'] ?></td>
                        <td><?php echo $carac[$i]['antecedentes'] ?></td>
                        <td><?php echo $carac[$i]['puntaje'] ?></td>
                        <td><?php echo $carac[$i]['caracterizacion_idtipoamp'] ?></td>
                        <td>
                        <a href="<?php echo Conexion::ruta(); ?>c-editarusuarios/v-<?php echo $datos[$i]['id_usuario']?>/">
                            <img src="<?php echo Conexion::ruta(); ?>/img/dashboard/edit.png" width="32" height="32">
                        </a>
                        </td>
                    </tr>
                <?php } ?>
                </tbody>
          </table>
        </div>
        <script src='//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
        <script src="../js/Dashboard.js"></script>

  </body>

</html>