<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="UTF-8" />
    <title>Caracterización</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/2.0.3/tailwind.min.css"/>
    <link rel="stylesheet" href="<?php echo Conexion::ruta();?>/css/usuarios.css" />
    <link rel="stylesheet" href="<?php echo Conexion::ruta();?>/css/crear_usu.css" />

    <body>
      <p class="texto">Crear Caracterización</p>
      <div class="Registro">
      <form method="POST" action="<?php echo Conexion::ruta();?>c-ccaracterizacion/">

        <input type="number" name="id_caracterizacion" class="validate[required,custom[onlyLetter],length[0,100]] feedback-input" placeholder="Id caracterización" autocomplete="off" required/>
        <input type="text" name="altura" class="validate[required,custom[onlyLetter],length[0,100]] feedback-input" placeholder="Altura" autocomplete="off" required/> 
        <input type="number" name="peso" class="validate[required,custom[onlyLetter],length[0,100]] feedback-input" placeholder="Peso" autocomplete="off" required/>
        <input type="hidden" name="crear">
        <input type="text" name="diametro_pierna" class="validate[required,custom[onlyLetter],length[0,100]] feedback-input" placeholder="Diametro pierna" autocomplete="off" required/>
        <input type="text" name="antecedentes" class="validate[required,custom[onlyLetter],length[0,100]] feedback-input" placeholder="Antecedentes" autocomplete="off" required/>
        <input type="number" name="puntaje" class="validate[required,custom[onlyLetter],length[0,100]] feedback-input" placeholder="Puntaje" autocomplete="off" required/>
        <input type="submit" value="Crear usuario" title="Crear caracterización">
        <br>
        <a href="<?php echo Conexion::ruta();?>c-usuarios/"><input type="button" value="Regresar"></a>
        </a>
      </form>
      <!-- partial -->

    </body>
  </head>
</html>