<?php session_start(); ?>
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>Dashboard - Usuarios</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <link rel='stylesheet' href='//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.1.0/css/font-awesome.min.css'>
  <link rel="stylesheet" href="<?php echo Conexion::ruta(); ?>/css/dashboard.css">
  <link rel="stylesheet" href="<?php echo Conexion::ruta(); ?>/css/table.css">

</head>

<body>
  <!-- partial:index.partial.html -->

  <body>
    <div id="menu-overlay"></div>
    <div id="menu-toggle" class="closed" data-title="Menu">
      <i class="fa fa-bars"></i>
      <i class="fa fa-times"></i>
    </div>

    <!-- MENU LATERAL -->
      <?php
        include "./view/menusidebar.phtml"; 
      ?>
     <!-- MENU LATERAL -->

    <section id="content">
      <!-- Boton de crear nuevo usuario -->
        <a href="<?php echo Conexion::ruta(); ?>c-creausuario/">
          <img src="<?php echo Conexion::ruta(); ?>/img/dashboard/crear.png" width="32" height="32">
          <h5>Crear</h5>
        </a>
      <div class="table">
        <div class="table-header">
          <div class="left-content">
            <h2>Usuarios</h2>
          </div>
        </div>
        <div class="table-wrapper">
          <table>
            <thead>
              <tr>
                <th>Documento</th>
                <th>Nombre</th>
                <th>Apellido</th>
                <th>Correo</th>
                <th>Clave</th>
                <th>Edad</th>
                <th>Celular</th>
                <th>Id caracterización</th>
                <th>Estado</th>
                <th>Opciones</th>
              </tr>
            </thead>
            <?php
            for ($i = 0; $i < sizeof($datos); $i++) {
            ?>

              <tbody>
                <tr>
                  <td><?php echo $datos[$i]['id_usuario']; ?></td>
                  <td><?php echo $datos[$i]['nombre']; ?></td>
                  <td><?php echo $datos[$i]['apellidos'] ?></td>
                  <td><a><?php echo $datos[$i]['email'] ?></a></td>
                  <td><?php echo $datos[$i]['clave'] ?></td>
                  <td><?php echo $datos[$i]['edad'] ?></td>
                  <td><?php echo $datos[$i]['celular'] ?></td>
                  <td><?php echo $datos[$i]['c_idcarac'] ?></td>
                  <td><?php echo $datos[$i]['estado'] ?></td>
                  <td>
                    <a href="<?php echo Conexion::ruta(); ?>c-editarusuarios/v-<?php echo $datos[$i]['id_usuario']?>/">
                        <img src="<?php echo Conexion::ruta(); ?>/img/dashboard/edit.png" width="32" height="32">
                    </a>
                    <a href="<?php echo Conexion::ruta(); ?>c-eliminarusuario/v-<?php echo $datos[$i]['id_usuario'] ?>/" onclick="return confirm('<?php echo "Desea eliminar el Usuario : " . $datos[$i]["nombre"] . " " . $datos[$i]["apellidos"] ?>')">
                      <img src="<?php echo Conexion::ruta(); ?>/img/dashboard/eliminar.png" width="32" height="32">
                    </a>
                    <a href="<?php echo Conexion::ruta(); ?>c-creacaracterizacion/">
                      Crear caracterización
                    </a>
                  </td>
                </tr>
              <?php } ?>
              </tbody>
          </table>
        </div>
        <script src='//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
        <script src="../js/Dashboard.js"></script>

  </body>

</html>