<!DOCTYPE html>
<!--[if IE 9]><html class="ie ie9"> <![endif]-->
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords" content="college, campus, university, courses, school, educational">
    <meta name="description" content="ATENA - College, University and campus template">
    <meta name="author" content="Ansonika">
    <title>P3PAM - Nosotros</title>
    <!-- icons -->
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
    <!-- Favicons-->
    <link rel="shortcut icon" href="img/logo/Logo - Simplificado - Fondo oscuro P3PAM.png" type="image/x-icon">
    <link rel="apple-touch-icon" type="image/x-icon" href="img/apple-touch-icon-57x57-precomposed.png">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="72x72" href="img/apple-touch-icon-72x72-precomposed.png">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="114x114" href="img/apple-touch-icon-114x114-precomposed.png">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="144x144" href="img/apple-touch-icon-144x144-precomposed.png">

    <!-- BASE CSS -->
    <link href="<?php echo Conexion::ruta();?>css/base.css" rel="stylesheet">
    

    <!--[if lt IE 9]>
      <script src="js/html5shiv.min.js"></script>
      <script src="js/respond.min.js"></script>
    <![endif]-->

</head>

<body>
<!--[if lte IE 8]>
    <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a>.</p>
<![endif]-->

<div id="preloader">
	<div class="pulse"></div>
</div><!-- Pulse Preloader -->

    <!-- Header================================================== -->
    <header>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3 col-sm-3 col-xs-3">
                <div id="logo">
                    <a href="<?php echo Conexion::ruta();?>c-home/">
                        <img src="<?php echo Conexion::ruta();?>img/logo/Logo - Horizontal Fondo Oscuro P3PAM.png" width="110" height="70" alt="Atena" data-retina="true">
                    </a>
                </div>
            </div>
            <nav class="col-md-9 col-sm-9 col-xs-9">
            <a class="cmn-toggle-switch cmn-toggle-switch__htx open_close" href="javascript:void(0);"><span>Menu mobile</span></a>
            <div class="main-menu">
                <div id="header_menu">
                    <img src="img/logo_mobile.png" width="125" height="40" alt="Atena" data-retina="true">
                </div>
                <a href="#" class="open_close" id="close_in"><i class="icon_close"></i></a>
                <ul>
                    <li><a href="<?php echo Conexion::ruta();?>c-home/">Home</a></li>
                    </li>
                    <li class="submenu">
                    <a href="javascript:void(0);" class="show-submenu">Nosotros <i class="icon-down-open-mini"></i></a>
                    <ul>
                        <li><a href="<?php echo Conexion::ruta();?>c-about/">Acerca de nosotros</a></li>
                        <li><a href="<?php echo Conexion::ruta();?>c-gallery/">Galería</a></li>
                    </ul>
                    </li>
                   
                    <li><a href="#" data-toggle="modal" data-target="#login">Iniciar sesión</a></li>
                    <li><a href="#" data-toggle="modal" data-target="#register">Registrase</a></li>
                    <li><a href="#search" id="search_bt"><i class=" icon-search"></i><span>Buscar</span></a></li>
                </ul>
            </div><!-- End main-menu -->
            </nav>
        </div>
    </div><!-- container -->
    </header><!-- End Header -->

        <div class="sub_header bg_2">
        	<div id="intro_txt">
			<h1>Prototipos y prótesis a <strong>Medida</strong>.</h1>
            </div>
		</div> <!--End sub_header -->
 
 		<div class="container_gray_bg">
        <div class="container margin_60">
        <div class="main_title">
            <h2>¿Por qué P3PAM?</h2>
            <p>Características de prototipos y prótesis</p>
            </div>

        	<div class="row">
        	<div class="col-md-4 col-sm-4">
            	<a class="box_feat">
                <i><ion-icon name="trending-up"></ion-icon></i>
            	<h3>Prótesis de alta calidad</h3>
                <p>Prótesis mandadas a fabricar utilizando los mejores materiales y con la más alta calidad, diseñadas específicamente para satisfacer 
                    las necesidades individuales de cada usuario.</p>
            </a>
            </div>
            <div class="col-md-4 col-sm-4">
            	<a class="box_feat">
                <i><ion-icon name="resize-outline"></ion-icon></i>
            	<h3>Protipos a medida</h3>
                <p>Creamos prototipos personalizados utilizando diseños previamente establecidos para garantizar la máxima comodidad y satisfacción del destinatario. </p>
            </a>
            </div>
            <div class="col-md-4 col-sm-4">
            	<a class="box_feat">
                <i><ion-icon name="card"></ion-icon></i>
            	<h3>Bajos recursos</h3>
                <p>Ofrecemos prótesis de alta calidad a precios asequibles para todas aquellas personas con discapacidad en las extremidades inferiores que no tienen los recursos económicos suficientes para obtener una prótesis de calidad.</p>
            </a>
            </div>
            </div><!--End row-->
            <div class="row">
            <div class="col-md-4 col-sm-4">
            	<a class="box_feat">
                <i><ion-icon name="search"></ion-icon></i>
            	<h3>Caracterización y costo</h3>
                <p>Proporcionamos prótesis de forma gratuita a aquellas personas que han sido identificadas previamente como elegibles. </p>
            </a>
            </div>
        	<div class="col-md-4 col-sm-4">
            	<a class="box_feat">
                <i><ion-icon name="analytics"></ion-icon></i>
            	<h3>Recolección</h3>
                <p>A través de eventos de caridad y recaudación de fondos, nos esforzamos por obtener los recursos necesarios para proporcionar prótesis a todas las personas que las necesiten.</p>
            </a>
            </div>
            <div class="col-md-4 col-sm-4">
            	<a class="box_feat">
                <i><ion-icon name="man"></ion-icon></i>
            	<h3>Público objetivo</h3>
                <p>Nos enfocamos en un público específico con el objetivo de satisfacer y ayudar a una necesidad particular.</p>
            </a>
            </div>
            </div><!--End row-->
            <br>

        </div><!--End container -->
        </div><!--End bg_gray_container -->
        
        <div class="container margin_60">
        	<div class="main_title">
                <h2>Sobre P3PAM ...</h2>
                <p>
                    ¿Por qué se creó?
                </p>
            </div>
            <div class="row">
                <div class="col-md-8 col-sm-8">
                    <h3>Protoipos y prótesis</h3>
                    <p>
                        El desarrollo de este proyecto busca brindar la oportunidad a personas en condición de discapacidad física de extremidades inferiores, a
                        acceder a una prótesis que les ayude a mejorar su calidad de vida, esto mediante una serie de actividades enfocadas a el desarrollo de
                        habilidades que permitan obtener los resultados esperados, desde la creación de la aplicación móvil, la caracterización del usuario,
                        pasando por el diseño y elaboración del prototipo en 3D a escala, como el financiamiento, por último la construcción y entrega de la
                        prótesis que le permita recuperar la independencia física al usuario beneficiado
                    </p>
                    <p>
                        Mediante el uso de
                        diferentes materiales de fabricación nacional que están siendo actualmente investigados y desarrollados por otros centros del Sena a nivel
                        nacional, principalmente se busca la reducción de los costos de producción de las prótesis que este proyecto busca entregar. Al hacer la
                        entrega de la prótesis se busca dignificar la vida de las víctimas, brindando la oportunidad de mejorar su confianza, superar sus dificultades
                        primarias y lograr a alcanzar su independencia física una vez arrebatada por alguna de las razones mencionadas en la identificación del
                        problema. Por medio del prototipado 3D a escala y entrega de la prótesis se pretende coadyuvar a todos los proyectos y programas
                        estatales para la sensibilización al tejido social y generar la responsabilidad social que se ha perdido a lo largo de los años, apoyando en la
                        reparación, integración e inclusión del más necesitado.

                    </p>

                    <h3>Integrantes</h3>
                    <p>
                        Integrantes quienes colaboran y ejecutan este proyecto.
                    </p>
                    <ul class="list_staff">
                        <li><figure><img src="<?php echo Conexion::ruta();?>img/teacher_1_thumb.jpg" alt="" class="img-circle"></figure>
                        <h5>Jhoan Useda</h5>
                        <p>Aprendiz</p>
                        </li>
                        <li><figure><img src="<?php echo Conexion::ruta();?>img/teacher_2_thumb.jpg" alt="" class="img-circle"></figure>
                        <h5>Jhonatan Romero</h5>
                        <p>Aprendiz</p>
                        </li>
                        <li><figure><img src="<?php echo Conexion::ruta();?>img/teacher_3_thumb.jpg" alt="" class="img-circle"></figure>
                        <h5>Carlos Orostegui</h5>
                        <p>Aprendiz</p>
                        </li>
                    </ul>
                </div>
                <div class="col-md-4 col-sm-4">
                    <div class="box_style_4">
                        <h4>Misión y objetivos</h4>
                        <p>
                            Desarrollar una aplicación móvil para la caracterización de discapacitados y la creación de prototipos en 3D de prótesis para la ayuda motriz a personas en condición de discapacidad de extremidades inferiores en la ciudad de Bucaramanga.

                        </p>
                        <ul class="list_order">
                            <li><span>1</span>Levantar la información pertinente acerca de la necesidad y los requerimientos funcionales y no funcionales, de acuerdo con las necesidades del cliente, a fin de generar un diagnóstico inicial como insumo para el diseño.</li>
                            <li><span>2</span>Elaborar el diseño de los modelos, los prototipos 3D, la interfaz gráfica de la solución y la base de datos, a fin de generar los insumos necesarios para el desarrollo de las aplicaciones correspondientes a la solución propuesta. </li>
                            <li><span>3</span>Desarrollar el código fuente necesario a fin de generar los prototipos.</li>
                            <li><span>4</span>Diseñar e implementar la arquitectura necesaria de hardware y software para la implementación de la solución final.</li>
                            <li><span>5</span>Implementar la solución de acuerdo con la arquitectura generada a fin de realizar las pruebas para entrega de la solución.</li>
                            <li><span>6</span>Documentar la solución a fin de permitir el soporte y la autogestión por parte del cliente, a nivel técnico y de usuario.</li>
                            <li><span>7</span>Adquirir y entregar la prótesis.</li>
                            <li><span>8</span>Realizar las pruebas piloto necesarias a fin de poner en marcha la solución en el cliente.</li>
                            <li><span>9</span>Validar de resultados obtenidos de pruebas pilotos de la aplicación diseñada, a partir de evaluaciones internas y externas por expertos en el tema para generar un aplicativo acorde con los requerimientos establecidos.</li>
                        </ul>
                    </div>
                </div>
            </div><!--End row -->
            <hr class="more_margin">
        </div><!--End container -->
        
        <div class="grid">
		<ul class="magnific-gallery">
						<li>
							<figure>
								<img src="<?php echo Conexion::ruta();?>img/gallery/pic_8.jpg" alt="">
								<figcaption>
								<div class="caption-content">
									<a href="<?php echo Conexion::ruta();?>img/gallery/large/pic_8.jpg" title="Photo title">
										<i class="pe-7s-albums"></i>
										<p>Your caption</p>
									</a>
								</div>
								</figcaption>
							</figure>
						</li>
						<li>
							<figure>
								<img src="<?php echo Conexion::ruta();?>img/gallery/pic_9.jpg" alt="">
								<figcaption>
								<div class="caption-content">
									<a href="<?php echo Conexion::ruta();?>img/gallery/large/pic_9.jpg" title="Photo title">
										<i class="pe-7s-albums"></i>
										<p>Your caption</p>
									</a>
								</div>
								</figcaption>
							</figure>
						</li>
						<li>
							<figure>
								<img src="<?php echo Conexion::ruta();?>img/gallery/pic_10.jpg" alt="">
								<figcaption>
								<div class="caption-content">
									<a href="<?php echo Conexion::ruta();?>img/gallery/large/pic_10.jpg" title="Photo title">
										<i class="pe-7s-albums"></i>
										<p>Your caption</p>
									</a>
								</div>
								</figcaption>
							</figure>
						</li>
						<li>
							<figure>
								<img src="<?php echo Conexion::ruta();?>img/gallery/pic_11.jpg" alt="">
								<figcaption>
								<div class="caption-content">
									<a href="<?php echo Conexion::ruta();?>img/gallery/large/pic_1.jpg" title="Photo title">
										<i class="pe-7s-albums"></i>
										<p>Your caption</p>
									</a>
								</div>
								</figcaption>
							</figure>
						</li>
					</ul>
		</div>

	<footer>
        <div class="container">
            <div class="row ">
                <div class="col-md-3 col-sm-3">
                    <p id="logo_footer">
                        <img src="<?php echo Conexion::ruta();?>img/logo/Logo - Simplificado - Fondo oscuro P3PAM.png" width="70" height="70" alt="Atena" data-retina="true">
                        <img src="<?php echo Conexion::ruta();?>img/logo/Logo - Horizontal Fondo Oscuro P3PAM.png" width="70" height="70" alt="Atena" data-retina="true">
                    </p>
                </div>
                <div class="col-md-3 col-sm-3">
                    <h4>Nosotros</h4>
                    <ul>
                        <li><a>Acerca de nosotros</a></li>
                        <li><a data-toggle="modal" data-target="#login">Iniciar sesión</a></li>
                        <li><a data-toggle="modal" data-target="#register">Registrase</a></li>
                        <li><a>Términos & condiciones</a></li>
                    </ul>
                </div>
                <div class="col-md-3 col-sm-3">
                    <h4>Contáctanos</h4>
                    <ul>
                        <li><a>Contacto</a></li>
                    </ul>
                    <ul id="contacts_footer">
                        <li>Línea de información - <a href="tel://033284322">+573215478520</a></li>
                        <li>Correo electrónico - <a href="#">info@p3pam.com</a></li>
                    </ul>
                </div>
            </div><!-- End row -->
        </div><!-- End container -->
        </footer><!-- End footer -->
        <div id="copy">
            <div class="container">
                 © P3PAM 2023 - Todos los derechos reservados.
            </div>
        </div><!-- End copy -->
	
<!-- Login modal -->   
<div class="modal fade" id="login" tabindex="-1" role="dialog" aria-labelledby="myLogin" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content modal-popup">
            <a href="#" class="close-link"><i class="icon_close_alt2"></i></a>
            <form action="#" class="popup-form" id="myLogin">
                <input type="text" class="form-control form-white" placeholder="Correo electrónico">
                <input type="text" class="form-control form-white" placeholder="Contraseña">
                <div class="crear">
                    <label for="#"data-toggle="modal" data-target="#register" style="color: gray">¿No tienes una cuenta? Registrate.</label>
                </div>
                <button type="submit" class="btn btn-submit">Iniciar sesión</button>
            </form>
        </div>
    </div>
</div>  
    
<!-- Register modal -->   
<div class="modal fade" id="register" tabindex="-1" role="dialog" aria-labelledby="myRegister" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content modal-popup">
            <a href="#" class="close-link"><i class="icon_close_alt2"></i></a>
            <form action="#" class="popup-form" id="myRegister">
                <input type="text" class="form-control form-white" placeholder="Nombres">
                <input type="text" class="form-control form-white" placeholder="Apellidos">
                <input type="text" class="form-control form-white" placeholder="Edad">
                <input type="email" class="form-control form-white" placeholder="Correo electrónico">
                <input type="text" class="form-control form-white" placeholder="Contraseña">
                <div class="checkbox-holder text-left">
                    <div class="checkbox">
                        <input type="checkbox" value="accept_2" id="check_2" name="check_2" />
                        <label for="check_2"><span>Acepto <strong>Términos &amp; Condiciones</strong></span></label>
                    </div>
                </div>
                <button type="submit" class="btn btn-submit">Registrarse</button>
            </form>
        </div>
    </div>
</div>
    
<!-- Search modal -->   
<div id="search">
    <button type="button" class="close">×</button>
    <form>
        <input type="search" value="" placeholder="type keyword(s) here" >
        <button type="submit" class="button">Search</button>
    </form>
</div>

<!-- Common scripts -->
<script src="<?php echo Conexion::ruta();?>js/jquery-1.11.2.min.js"></script>
<script src="<?php echo Conexion::ruta();?>js/common_scripts_min.js"></script>
<script src="<?php echo Conexion::ruta();?>js/functions.js"></script>
<script src="<?php echo Conexion::ruta();?>assets/validate.js"></script>

</body>
</html>