<?php session_start(); ?>

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>CodePen - Responsive Admin Screen</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <link rel='stylesheet' href='//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.1.0/css/font-awesome.min.css'>
  <link rel="stylesheet" href="<?php echo Conexion::ruta(); ?>/css/dashboard.css">

</head>

<body>
  <!-- partial:index.partial.html -->

  <body>
    <div id="menu-overlay"></div>
    <div id="menu-toggle" class="closed" data-title="Menu">
      <i class="fa fa-bars"></i>
      <i class="fa fa-times"></i>
    </div>
    <header id="main-header">
      <nav id="sidenav">
        <div id="sidenav-header">
          <div id="profile-picture">
            <img src="http://www.gravatar.com/avatar/fa4df8540bab3cb38f7dfa60c6e0522c.png" />
          </div>
          <a href="#" id="profile-link">Jesse Couch</a>
        </div>
        <div id="account-actions">
          <a href="#" data-title="Settings"><i class="fa fa-cog"></i></a>
        </div>
        <ul id="main-nav">
          <li class="active">
            <a href="<?php echo Conexion::ruta(); ?>c-dashboard/">
              <i class="fa fa-tachometer"></i>
              Dashboard
            </a>
          </li>
          <li>
            <a href="<?php echo Conexion::ruta(); ?>c-roles/">
              <i class="fa fa-check-square-o"></i>
              Tabla Rol
            </a>
          </li>
          <li>
            <a href="<?php echo Conexion::ruta(); ?>c-usuarios/">
              <i class="fa fa-check-square-o"></i>
              Tabla Usuario
            </a>
          </li>
          <li>
            <a href="<?php echo Conexion::ruta(); ?>c-rolesusuarios/">
              <i class="fa fa-check-square-o"></i>
              Tabla Rol Usuario
            </a>
          </li>
          <li class="active">
            <a href="<?php echo Conexion::ruta(); ?>c-rolesusuarios/">
              <i class="fa fa-check-square-o"></i>
              Tabla Caracterización
            </a>
          </li>
        </ul>
      </nav>
      <form id="admin-search">
        <input type="text" id="search-field" placeholder="Search" />
        <label for="search-field" id="search-label" title="Search"><i class="fa fa-search"></i></label>
      </form>
      <div id="header_logo">
        <a href="#">Logo</a>
      </div>
    </header>
    <section id="content">
      <header id="content-header">
        Header content
      </header>
      <nav id="tabs">
        <ul>
          <li class="active" data-target="knowledge">Knowledge</li>
          <li data-target="activity">Activity</li>
          <li data-target="friends">Friends</li>
        </ul>
      </nav>
      <div class="tab-target targeted" id="knowledge">
        <p>Knowledge Content</p>
        <p>Bushwick VHS single-origin coffee, direct trade selfies Tonx chillwave fashion axe McSweeney's roof party four loko Williamsburg ugh. Hashtag farm-to-table keytar, gentrify roof party Vice stumptown polaroid sriracha fingerstache Intelligentsia bitters. You probably haven't heard of them 8-bit pickled pug, cardigan photo booth Schlitz Kickstarter pork belly art party raw denim street art readymade single-origin coffee Carles. Banh mi Pinterest cliche, YOLO ennui quinoa salvia brunch messenger bag twee kitsch sartorial. Cornhole bitters chambray irony, wayfarers PBR&B disrupt Marfa. Austin ennui bespoke Schlitz shabby chic, meggings iPhone. Wes Anderson kale chips you probably haven't heard of them, freegan Vice scenester seitan Cosby sweater Schlitz pop-up dreamcatcher butcher artisan Truffaut roof party.</p>

        <p>Flexitarian art party keffiyeh, PBR&B seitan Carles Godard XOXO cred Brooklyn pickled. YOLO synth butcher post-ironic, pop-up organic artisan banjo PBR try-hard dreamcatcher plaid messenger bag brunch distillery. McSweeney's cray squid, roof party Blue Bottle irony kitsch before they sold out lo-fi asymmetrical shabby chic twee Tonx pickled try-hard. Artisan hella you probably haven't heard of them selvage, jean shorts locavore photo booth fanny pack mumblecore flannel before they sold out semiotics. Intelligentsia sustainable semiotics fanny pack distillery chillwave deep v, VHS dreamcatcher biodiesel synth. Locavore quinoa American Apparel, tote bag skateboard bespoke Wes Anderson pork belly cliche cred Brooklyn blog authentic flexitarian. Try-hard cray Pitchfork, hella Truffaut flexitarian sartorial sriracha Williamsburg Cosby sweater plaid meggings Helvetica.</p>
      </div>
      <div class="tab-target" id="activity">
        Activity Content
      </div>
      <div class="tab-target" id="friends">
        Friends Content
      </div>
    </section>
    <footer></footer>
  </body>
  <!-- partial -->
  <script src='//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
  <script src="../js/Dashboard.js"></script>

</body>

</html>