<!DOCTYPE html>
<html lang="es" >
	<head>
	  <meta charset="UTF-8">
	  <title>404 Error Page</title>
	</head>
	<body>
		<p class="subtitle">
			Página No encontrada <br /> intente de nuevo más tarde o consulte al Administrador del sistema.
		</p>
		<!-- <div align="center">
			<a class="btn-back" href="<?php //echo Conectar::ruta();?>c-home/">Regresar al Inicio</a>
		</div> -->
		<!-- partial -->
	</body>
</html>
