<!DOCTYPE html>
<!--[if IE 9]><html class="ie ie9"> <![endif]-->
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords" content="college, campus, university, courses, school, educational">
    <meta name="description" content="ATENA - College, University and campus template">
    <meta name="author" content="Ansonika">
    <title>P3PAM - Galería</title>

    <!-- Favicons-->
    <link rel="shortcut icon" href="img/logo/Logo - Simplificado - Fondo oscuro P3PAM.png" type="image/x-icon">
    <link rel="apple-touch-icon" type="image/x-icon" href="img/apple-touch-icon-57x57-precomposed.png">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="72x72" href="img/apple-touch-icon-72x72-precomposed.png">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="114x114" href="img/apple-touch-icon-114x114-precomposed.png">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="144x144" href="img/apple-touch-icon-144x144-precomposed.png">

    <!-- BASE CSS -->
    <link href="<?php echo Conexion::ruta();?>css/base.css" rel="stylesheet">

    <!--[if lt IE 9]>
      <script src="js/html5shiv.min.js"></script>
      <script src="js/respond.min.js"></script>
    <![endif]-->

</head>

<body>

<!--[if lte IE 8]>
    <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a>.</p>
<![endif]-->

<div id="preloader">
	<div class="pulse"></div>
</div><!-- Pulse Preloader -->

    <!-- Header================================================== -->
    <header>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3 col-sm-3 col-xs-3">
                <div id="logo">
                    <a href="<?php echo Conexion::ruta();?>c-home/">
						<img src="<?php echo Conexion::ruta();?>img/logo/Logo - Horizontal Fondo Oscuro P3PAM.png" width="110" height="70" alt="Atena" data-retina="true">
					</a>
                </div>
            </div>
            <nav class="col-md-9 col-sm-9 col-xs-9">
            <a class="cmn-toggle-switch cmn-toggle-switch__htx open_close" href="javascript:void(0);"><span>Menu mobile</span></a>
            <div class="main-menu">
                <div id="header_menu">
                    <img src="img/logo_mobile.png" width="125" height="40" alt="Atena" data-retina="true">
                </div>
                <a href="#" class="open_close" id="close_in"><i class="icon_close"></i></a>
                <ul>
                    <li><a href="<?php echo Conexion::ruta();?>c-home/">Home</a></li>

                    <li class="submenu">
                    <a href="javascript:void(0);" class="show-submenu">Nosotros <i class="icon-down-open-mini"></i></a>
                    <ul>
                        <li><a href="<?php echo Conexion::ruta();?>c-about/">Acerca de nosotros</a></li>
                        <li><a href="<?php echo Conexion::ruta();?>c-gallery/">Galería</a></li>
                    </ul>
                    </li>
                    <li><a href="#" data-toggle="modal" data-target="#login">Iniciar sesión</a></li>
                    <li><a href="#" data-toggle="modal" data-target="#register">Registrase</a></li>
                    <li><a href="#search" id="search_bt"><i class=" icon-search"></i><span>Buscar</span></a></li>
                </ul>
            </div><!-- End main-menu -->
            </nav>
        </div>
    </div><!-- container -->
    </header><!-- End Header -->
    
     <div class="sub_header bg_4">
        	<div id="intro_txt">
			<h1>P3PAM <strong>Galería</strong></h1>
            <p>Galería de algunos de los resultados de personas con sus prótesis.</p>
            </div>
		</div> <!--End sub_header -->
        
        <div id="position">
            <div class="container">
                <ul>
                    <li><a href="#">Home</a></li>
                    <li><a href="#">Category</a></li>
                    <li>Page active</li>
                </ul>
            </div>
        </div><!-- Position -->

		<div class="container margin_60">
	<section class="grid">
            <div class="main_title">
                <h2>Aquí algunas fotos ...</h2>
                <p>Cum doctus civibus efficiantur in imperdiet deterruisset.</p>
                </div>
				<div class="row">
					<ul class="magnific-gallery">
						<li>
							<figure>
								<img src="<?php echo Conexion::ruta();?>img/gallery/pic_4.jpg" alt="">
								<figcaption>
								<div class="caption-content">
									<a href="<?php echo Conexion::ruta();?>img/gallery/large/pic_4.jpg" title="Photo title" data-effect="mfp-move-horizontal">
										<i class="pe-7s-albums"></i>
										<p>Your caption</p>
								</a>
								</div>
								</figcaption>
							</figure>
						</li>
						<li>
							<figure>
								<img src="<?php echo Conexion::ruta();?>img/gallery/pic_5.jpg" alt="">
								<figcaption>
								<div class="caption-content">
                                    	<a href="<?php echo Conexion::ruta();?>img/gallery/large/pic_5.jpg" title="Photo title" data-effect="mfp-move-horizontal">
                                        <i class="pe-7s-albums"></i>
										<p>Your caption</p>
									   </a>
								</div>
                             
								</figcaption>
							</figure>
						</li>
						<li>
							<figure>
								<img src="<?php echo Conexion::ruta();?>img/gallery/pic_6.jpg" alt="">
								<figcaption>
								<div class="caption-content">
										<a href="<?php echo Conexion::ruta();?>img/gallery/large/pic_6.jpg" title="Photo title" data-effect="mfp-move-horizontal">
										<i class="pe-7s-albums"></i>
										<p>Your caption</p>
									</a>
								</div>
								</figcaption>
							</figure>
						</li>
						<li>
							<figure>
								<img src="<?php echo Conexion::ruta();?>img/gallery/pic_7.jpg" alt="">
								<figcaption>
								<div class="caption-content">
									<a href="<?php echo Conexion::ruta();?>img/gallery/large/pic_7.jpg" title="Photo title">
										<i class="pe-7s-albums"></i>
										<p>Your caption</p>
									</a>
								</div>
								</figcaption>
							</figure>
						</li>
					</ul>
				</div>
				<div class="row">
					<ul class="magnific-gallery">
						<li>
							<figure>
								<img src="<?php echo Conexion::ruta();?>img/gallery/pic_8.jpg" alt="">
								<figcaption>
								<div class="caption-content">
									<a href="<?php echo Conexion::ruta();?>img/gallery/large/pic_8.jpg" title="Photo title">
										<i class="pe-7s-albums"></i>
										<p>Your caption</p>
									</a>
								</div>
								</figcaption>
							</figure>
						</li>
						<li>
							<figure>
								<img src="<?php echo Conexion::ruta();?>img/gallery/pic_9.jpg" alt="">
								<figcaption>
								<div class="caption-content">
									<a href="<?php echo Conexion::ruta();?>img/gallery/large/pic_9.jpg" title="Photo title">
										<i class="pe-7s-albums"></i>
										<p>Your caption</p>
									</a>
								</div>
								</figcaption>
							</figure>
						</li>
						<li>
							<figure>
								<img src="<?php echo Conexion::ruta();?>img/gallery/pic_10.jpg" alt="">
								<figcaption>
								<div class="caption-content">
									<a href="<?php echo Conexion::ruta();?>img/gallery/large/pic_10.jpg" title="Photo title">
										<i class="pe-7s-albums"></i>
										<p>Your caption</p>
									</a>
								</div>
								</figcaption>
							</figure>
						</li>
						<li>
							<figure>
								<img src="<?php echo Conexion::ruta();?>img/gallery/pic_11.jpg" alt="">
								<figcaption>
								<div class="caption-content">
									<a href="<?php echo Conexion::ruta();?>img/gallery/large/pic_1.jpg" title="Photo title">
										<i class="pe-7s-albums"></i>
										<p>Your caption</p>
									</a>
								</div>
								</figcaption>
							</figure>
						</li>
					</ul>
				</div>		
		</section>
        
        <section class="grid">
			<div class="container margin_60">
            <div class="main_title">
                <h2>Aquí algunos videos ...</h2>
                <p>Cum doctus civibus efficiantur in imperdiet deterruisset.</p>
                </div>
                	<div class="row">
					<ul class="magnific-gallery">
						<li>
							<figure>
								<img src="<?php echo Conexion::ruta();?>img/gallery/pic_2.jpg" alt="">
								<figcaption>
								<div class="caption-content">
									<a href="https://vimeo.com/45830194" class="video_pop" title="Video Vimeo">
										<i class="pe-7s-film"></i>
										<p>Your caption</p>
								</a>
								</div>
								</figcaption>
							</figure>
						</li>
				
						<li>
							<figure>
								<img src="<?php echo Conexion::ruta();?>img/gallery/pic_13.jpg" alt="">
								<figcaption>
								<div class="caption-content">
									 <a href="https://www.youtube.com/watch?v=Zz5cu72Gv5Y" class="video_pop" title="Video Youtube">
										<i class="pe-7s-film"></i>
										<p>Your caption</p>
									</a>
								</div>
								</figcaption>
							</figure>
						</li>
						<li>
							<figure>
								<img src="<?php echo Conexion::ruta();?>img/gallery/pic_4.jpg" alt="">
								<figcaption>
								<div class="caption-content">
									<a href="https://vimeo.com/45830194" class="video_pop" title="Video Vimeo">
										<i class="pe-7s-film"></i>
										<p>Your caption</p>
									</a>
								</div>
								</figcaption>
							</figure>
						</li>
					</ul>
				</div>
			</div>
		</section>
        	</div>
 
	<footer>
        <div class="container">
            <div class="row ">
                <div class="col-md-3 col-sm-3">
                    <p id="logo_footer">
                        <img src="<?php echo Conexion::ruta();?>img/logo/Logo - Simplificado - Fondo oscuro P3PAM.png" width="70" height="70" alt="Atena" data-retina="true">
                        <img src="<?php echo Conexion::ruta();?>img/logo/Logo - Horizontal Fondo Oscuro P3PAM.png" width="70" height="70" alt="Atena" data-retina="true">
                    </p>
                </div>
                <div class="col-md-3 col-sm-3">
                    <h4>Nosotros</h4>
                    <ul>
                        <li><a>Acerca de nosotros</a></li>
                        <li><a data-toggle="modal" data-target="#login">Iniciar sesión</a></li>
                        <li><a data-toggle="modal" data-target="#register">Registrase</a></li>
                        <li><a>Términos & condiciones</a></li>
                    </ul>
                </div>
                <div class="col-md-3 col-sm-3">
                    <h4>Contáctanos</h4>
                    <ul>
                        <li><a>Contacto</a></li>
                    </ul>
                    <ul id="contacts_footer">
                        <li>Línea de información - <a href="tel://033284322">+573215478520</a></li>
                        <li>Correo electrónico - <a href="#">info@p3pam.com</a></li>
                    </ul>
                </div>
            </div><!-- End row -->
        </div><!-- End container -->
        </footer><!-- End footer -->
        <div id="copy">
            <div class="container">
                 © P3PAM 2023 - Todos los derechos reservados.
            </div>
        </div><!-- End copy -->
	
<!-- Login modal -->   
<div class="modal fade" id="login" tabindex="-1" role="dialog" aria-labelledby="myLogin" aria-hidden="true">
	<div class="modal-dialog">
        <div class="modal-content modal-popup">
            <a href="#" class="close-link"><i class="icon_close_alt2"></i></a>
            <form action="#" class="popup-form" id="myLogin">
                <input type="text" class="form-control form-white" placeholder="Correo electrónico">
                <input type="text" class="form-control form-white" placeholder="Contraseña">
                <div class="crear">
                    <label for="#"data-toggle="modal" data-target="#register" style="color: gray">¿No tienes una cuenta? Registrate.</label>
                </div>
                <button type="submit" class="btn btn-submit">Iniciar sesión</button>
            </form>
        </div>
    </div>
</div>  
    
<!-- Register modal -->   
<div class="modal fade" id="register" tabindex="-1" role="dialog" aria-labelledby="myRegister" aria-hidden="true">
	<div class="modal-dialog">
        <div class="modal-content modal-popup">
            <a href="#" class="close-link"><i class="icon_close_alt2"></i></a>
            <form action="#" class="popup-form" id="myRegister">
                <input type="text" class="form-control form-white" placeholder="Nombres">
                <input type="text" class="form-control form-white" placeholder="Apellidos">
                <input type="text" class="form-control form-white" placeholder="Edad">
                <input type="email" class="form-control form-white" placeholder="Correo electrónico">
                <input type="text" class="form-control form-white" placeholder="Contraseña">
                <div class="checkbox-holder text-left">
                    <div class="checkbox">
                        <input type="checkbox" value="accept_2" id="check_2" name="check_2" />
                        <label for="check_2"><span>Acepto <strong>Términos &amp; Condiciones</strong></span></label>
                    </div>
                </div>
                <button type="submit" class="btn btn-submit">Registrarse</button>
            </form>
        </div>
    </div>
</div>
    
<!-- Search modal -->   
<div id="search">
    <button type="button" class="close">×</button>
    <form>
        <input type="search" value="" placeholder="type keyword(s) here" >
        <button type="submit" class="button">Search</button>
    </form>
</div>

<!-- Common scripts -->
<script src="<?php echo Conexion::ruta();?>js/jquery-1.11.2.min.js"></script>
<script src="<?php echo Conexion::ruta();?>js/common_scripts_min.js"></script>
<script src="<?php echo Conexion::ruta();?>js/functions.js"></script>
<script src="<?php echo Conexion::ruta();?>assets/validate.js"></script>

</body>
</html>